name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on:
  push:
    branches: [ main ]
  # pull_request:
    # branches: [ main ]

jobs:
  Explore-GitHub-Actions:
    name: Run test on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ Job triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ Job running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” Branch: ${{ github.ref }}, Repository: ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository was cloned."
      - run: echo "ğŸ–¥ï¸ Test code."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ Job status: ${{ job.status }}."
